louvre_reservation_home:
    path:     /
    defaults:
        _controller: LouvreReservationBundle:Reservation:index

louvre_reservation_calendar:
    path:     /calendar
    defaults:
        _controller: LouvreReservationBundle:Reservation:calendar