louvre_reservation_home:
    path:     /
    defaults:
        _controller: LouvreReservationBundle:Reservation:index

louvre_reservation_calendar:
    path:     /calendar
    defaults:
        _controller: LouvreReservationBundle:Reservation:calendar

louvre_reservation_ticketing:
    path:     /ticketing
    defaults:
        _controller: LouvreReservationBundle:Reservation:ticketing

louvre_reservation_confirmation:
    path:     /confirmation
    defaults:
        _controller: LouvreReservationBundle:Reservation:confirmation