services:
    louvre_reservation.agecalculator:
        class: Louvre\ReservationBundle\AgeCalculator\LouvreAgeCalculator

    louvre_reservation.pricecalculator:
        class: Louvre\ReservationBundle\PriceCalculator\LouvrePriceCalculator
        arguments:
            - "@louvre_reservation.agecalculator"

    louvre_reservation.ticketcounter:
        class: Louvre\ReservationBundle\TicketCounter\LouvreTicketCounter

    louvre_reservation.codegenerator:
        class: Louvre\ReservationBundle\Services\CodeGenerator\LouvreCodeGenerator